/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) race_car_dynamics_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 3, 4};
static const casadi_int casadi_s1[12] = {4, 4, 0, 0, 0, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s2[12] = {4, 4, 0, 2, 4, 5, 5, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[9] = {4, 2, 0, 1, 4, 3, 0, 1, 2};
static const casadi_int casadi_s5[11] = {2, 4, 0, 1, 2, 3, 4, 1, 1, 1, 0};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s10[3] = {4, 0, 0};

/* race_car_dynamics_impl_dae_jac_x_xdot_u_z:(i0[4],i1[4],i2[2],i3[],i4[],i5[9])->(o0[4x4,5nz],o1[4x4,4nz],o2[4x2,4nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, *w9=w+13, w10, w11, *w14=w+18, *w15=w+20, w16, w17, *w18=w+24, *w19=w+27, *w20=w+32, *w21=w+36;
  /* #0: @0 = zeros(4x4,5nz) */
  casadi_clear(w0, 5);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #4: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #5: @5 = tan(@4) */
  w5 = tan( w4 );
  /* #6: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #7: @6 = 2.5 */
  w6 = 2.5000000000000000e+00;
  /* #8: @5 = (@5/@6) */
  w5 /= w6;
  /* #9: @6 = atan(@5) */
  w6 = atan( w5 );
  /* #10: @7 = (@2+@6) */
  w7  = (w2+w6);
  /* #11: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #12: @9 = ones(4x1,3nz) */
  casadi_fill(w9, 3, 1.);
  /* #13: {NULL, NULL, @10, NULL} = vertsplit(@9) */
  w10 = w9[2];
  /* #14: @8 = (@8*@10) */
  w8 *= w10;
  /* #15: @8 = (@1*@8) */
  w8  = (w1*w8);
  /* #16: @8 = (-@8) */
  w8 = (- w8 );
  /* #17: @2 = (@2+@6) */
  w2 += w6;
  /* #18: @11 = cos(@2) */
  w11 = cos( w2 );
  /* #19: @11 = (@11*@10) */
  w11 *= w10;
  /* #20: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #21: @12 = 00 */
  /* #22: @13 = 00 */
  /* #23: @14 = vertcat(@8, @11, @12, @13) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w11;
  /* #24: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<2; ++i) *rr++ = (- *cs++ );
  /* #25: @15 = @14[:2] */
  for (rr=w15, ss=w14+0; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #26: (@0[:4:2] = @15) */
  for (rr=w0+0, ss=w15; rr!=w0+4; rr+=2) *rr = *ss++;
  /* #27: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #28: @11 = ones(4x1,1nz) */
  w11 = 1.;
  /* #29: {NULL, NULL, NULL, @10} = vertsplit(@11) */
  w10 = w11;
  /* #30: @8 = (@8*@10) */
  w8 *= w10;
  /* #31: @11 = sin(@2) */
  w11 = sin( w2 );
  /* #32: @11 = (@11*@10) */
  w11 *= w10;
  /* #33: @16 = sin(@6) */
  w16 = sin( w6 );
  /* #34: @17 = 0.666667 */
  w17 = 6.6666666666666663e-01;
  /* #35: @17 = (@17*@10) */
  w17 *= w10;
  /* #36: @16 = (@16*@17) */
  w16 *= w17;
  /* #37: @12 = 00 */
  /* #38: @9 = vertcat(@8, @11, @16, @12) */
  rr=w9;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w16;
  /* #39: @9 = (-@9) */
  for (i=0, rr=w9, cs=w9; i<3; ++i) *rr++ = (- *cs++ );
  /* #40: @18 = @9[:3] */
  for (rr=w18, ss=w9+0; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #41: (@0[1, 3, 4] = @18) */
  for (cii=casadi_s0, rr=w0, ss=w18; cii!=casadi_s0+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #42: @19 = @0' */
  casadi_trans(w0,casadi_s2, w19, casadi_s1, iw);
  /* #43: output[0][0] = @19 */
  casadi_copy(w19, 5, res[0]);
  /* #44: @20 = zeros(4x4,4nz) */
  casadi_clear(w20, 4);
  /* #45: @21 = ones(4x1) */
  casadi_fill(w21, 4, 1.);
  /* #46: (@20[:4] = @21) */
  for (rr=w20+0, ss=w21; rr!=w20+4; rr+=1) *rr = *ss++;
  /* #47: @21 = @20' */
  casadi_trans(w20,casadi_s3, w21, casadi_s3, iw);
  /* #48: output[1][0] = @21 */
  casadi_copy(w21, 4, res[1]);
  /* #49: @21 = zeros(2x4,4nz) */
  casadi_clear(w21, 4);
  /* #50: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #51: @8 = 0.4 */
  w8 = 4.0000000000000002e-01;
  /* #52: @15 = ones(2x1) */
  casadi_fill(w15, 2, 1.);
  /* #53: {@11, @16} = vertsplit(@15) */
  w11 = w15[0];
  w16 = w15[1];
  /* #54: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #55: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #56: @16 = (@16/@4) */
  w16 /= w4;
  /* #57: @3 = (@3*@16) */
  w3 *= w16;
  /* #58: @8 = (@8*@3) */
  w8 *= w3;
  /* #59: @3 = 1 */
  w3 = 1.;
  /* #60: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #61: @3 = (@3+@5) */
  w3 += w5;
  /* #62: @8 = (@8/@3) */
  w8 /= w3;
  /* #63: @7 = (@7*@8) */
  w7 *= w8;
  /* #64: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #65: @7 = (-@7) */
  w7 = (- w7 );
  /* #66: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #67: @2 = (@2*@8) */
  w2 *= w8;
  /* #68: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #69: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #70: @1 = (@1/@3) */
  w1 /= w3;
  /* #71: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #72: @6 = (@6*@8) */
  w6 *= w8;
  /* #73: @1 = (@1*@6) */
  w1 *= w6;
  /* #74: @20 = vertcat(@7, @2, @1, @11) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w11;
  /* #75: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #76: (@21[:4] = @20) */
  for (rr=w21+0, ss=w20; rr!=w21+4; rr+=1) *rr = *ss++;
  /* #77: @20 = @21' */
  casadi_trans(w21,casadi_s5, w20, casadi_s4, iw);
  /* #78: output[2][0] = @20 */
  casadi_copy(w20, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real race_car_dynamics_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s8;
    case 5: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 40;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
