/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) race_car_dynamics_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 3, 4};
static const casadi_int casadi_s1[12] = {4, 4, 0, 0, 0, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s2[12] = {4, 4, 0, 2, 4, 5, 5, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[9] = {4, 2, 0, 1, 4, 3, 0, 1, 2};
static const casadi_int casadi_s5[11] = {2, 4, 0, 1, 2, 3, 4, 1, 1, 1, 0};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* race_car_dynamics_impl_dae_fun_jac_x_xdot_u:(i0[4],i1[4],i2[2],i3[],i4[],i5[9])->(o0[4],o1[4x4,5nz],o2[4x4,4nz],o3[4x2,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w16=w+19, *w17=w+23, *w18=w+28, *w21=w+31, *w22=w+33, *w23=w+35, *w24=w+38;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 4, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #4: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #5: @5 = tan(@4) */
  w5 = tan( w4 );
  /* #6: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #7: @6 = 2.5 */
  w6 = 2.5000000000000000e+00;
  /* #8: @5 = (@5/@6) */
  w5 /= w6;
  /* #9: @6 = atan(@5) */
  w6 = atan( w5 );
  /* #10: @7 = (@2+@6) */
  w7  = (w2+w6);
  /* #11: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #12: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #13: @2 = (@2+@6) */
  w2 += w6;
  /* #14: @10 = sin(@2) */
  w10 = sin( w2 );
  /* #15: @11 = (@1*@10) */
  w11  = (w1*w10);
  /* #16: @12 = 1.5 */
  w12 = 1.5000000000000000e+00;
  /* #17: @12 = (@1/@12) */
  w12  = (w1/w12);
  /* #18: @13 = sin(@6) */
  w13 = sin( w6 );
  /* #19: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #20: @15 = input[2][0] */
  w15 = arg[2] ? arg[2][0] : 0;
  /* #21: @16 = vertcat(@9, @11, @14, @15) */
  rr=w16;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w15;
  /* #22: @0 = (@0-@16) */
  for (i=0, rr=w0, cs=w16; i<4; ++i) (*rr++) -= (*cs++);
  /* #23: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #24: @17 = zeros(4x4,5nz) */
  casadi_clear(w17, 5);
  /* #25: @9 = sin(@7) */
  w9 = sin( w7 );
  /* #26: @18 = ones(4x1,3nz) */
  casadi_fill(w18, 3, 1.);
  /* #27: {NULL, NULL, @11, NULL} = vertsplit(@18) */
  w11 = w18[2];
  /* #28: @9 = (@9*@11) */
  w9 *= w11;
  /* #29: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #30: @9 = (-@9) */
  w9 = (- w9 );
  /* #31: @14 = cos(@2) */
  w14 = cos( w2 );
  /* #32: @14 = (@14*@11) */
  w14 *= w11;
  /* #33: @14 = (@1*@14) */
  w14  = (w1*w14);
  /* #34: @19 = 00 */
  /* #35: @20 = 00 */
  /* #36: @21 = vertcat(@9, @14, @19, @20) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w14;
  /* #37: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) *rr++ = (- *cs++ );
  /* #38: @22 = @21[:2] */
  for (rr=w22, ss=w21+0; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #39: (@17[:4:2] = @22) */
  for (rr=w17+0, ss=w22; rr!=w17+4; rr+=2) *rr = *ss++;
  /* #40: @9 = ones(4x1,1nz) */
  w9 = 1.;
  /* #41: {NULL, NULL, NULL, @14} = vertsplit(@9) */
  w14 = w9;
  /* #42: @8 = (@8*@14) */
  w8 *= w14;
  /* #43: @10 = (@10*@14) */
  w10 *= w14;
  /* #44: @9 = 0.666667 */
  w9 = 6.6666666666666663e-01;
  /* #45: @9 = (@9*@14) */
  w9 *= w14;
  /* #46: @13 = (@13*@9) */
  w13 *= w9;
  /* #47: @19 = 00 */
  /* #48: @18 = vertcat(@8, @10, @13, @19) */
  rr=w18;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w13;
  /* #49: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #50: @23 = @18[:3] */
  for (rr=w23, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #51: (@17[1, 3, 4] = @23) */
  for (cii=casadi_s0, rr=w17, ss=w23; cii!=casadi_s0+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #52: @24 = @17' */
  casadi_trans(w17,casadi_s2, w24, casadi_s1, iw);
  /* #53: output[1][0] = @24 */
  casadi_copy(w24, 5, res[1]);
  /* #54: @0 = zeros(4x4,4nz) */
  casadi_clear(w0, 4);
  /* #55: @16 = ones(4x1) */
  casadi_fill(w16, 4, 1.);
  /* #56: (@0[:4] = @16) */
  for (rr=w0+0, ss=w16; rr!=w0+4; rr+=1) *rr = *ss++;
  /* #57: @16 = @0' */
  casadi_trans(w0,casadi_s3, w16, casadi_s3, iw);
  /* #58: output[2][0] = @16 */
  casadi_copy(w16, 4, res[2]);
  /* #59: @16 = zeros(2x4,4nz) */
  casadi_clear(w16, 4);
  /* #60: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #61: @8 = 0.4 */
  w8 = 4.0000000000000002e-01;
  /* #62: @22 = ones(2x1) */
  casadi_fill(w22, 2, 1.);
  /* #63: {@10, @13} = vertsplit(@22) */
  w10 = w22[0];
  w13 = w22[1];
  /* #64: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #65: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #66: @13 = (@13/@4) */
  w13 /= w4;
  /* #67: @3 = (@3*@13) */
  w3 *= w13;
  /* #68: @8 = (@8*@3) */
  w8 *= w3;
  /* #69: @3 = 1 */
  w3 = 1.;
  /* #70: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #71: @3 = (@3+@5) */
  w3 += w5;
  /* #72: @8 = (@8/@3) */
  w8 /= w3;
  /* #73: @7 = (@7*@8) */
  w7 *= w8;
  /* #74: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #75: @7 = (-@7) */
  w7 = (- w7 );
  /* #76: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #77: @2 = (@2*@8) */
  w2 *= w8;
  /* #78: @1 = (@1*@2) */
  w1 *= w2;
  /* #79: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #80: @6 = (@6*@8) */
  w6 *= w8;
  /* #81: @12 = (@12*@6) */
  w12 *= w6;
  /* #82: @0 = vertcat(@7, @1, @12, @10) */
  rr=w0;
  *rr++ = w7;
  *rr++ = w1;
  *rr++ = w12;
  *rr++ = w10;
  /* #83: @0 = (-@0) */
  for (i=0, rr=w0, cs=w0; i<4; ++i) *rr++ = (- *cs++ );
  /* #84: (@16[:4] = @0) */
  for (rr=w16+0, ss=w0; rr!=w16+4; rr+=1) *rr = *ss++;
  /* #85: @0 = @16' */
  casadi_trans(w16,casadi_s5, w0, casadi_s4, iw);
  /* #86: output[3][0] = @0 */
  casadi_copy(w0, 4, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real race_car_dynamics_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s8;
    case 5: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 43;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
