/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) race_car_dynamics_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {1, 3, 4};
static const casadi_int casadi_s1[12] = {4, 4, 0, 0, 0, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s2[12] = {4, 4, 0, 2, 4, 5, 5, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s8[3] = {4, 0, 0};

/* race_car_dynamics_impl_dae_fun_jac_x_xdot_z:(i0[4],i1[4],i2[2],i3[],i4[],i5[9])->(o0[4],o1[4x4,5nz],o2[4x4,4nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, *w11=w+14, *w12=w+18, *w13=w+23, *w16=w+26, *w17=w+28, *w18=w+30, *w19=w+33;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 4, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #4: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #5: @4 = tan(@4) */
  w4 = tan( w4 );
  /* #6: @3 = (@3*@4) */
  w3 *= w4;
  /* #7: @4 = 2.5 */
  w4 = 2.5000000000000000e+00;
  /* #8: @3 = (@3/@4) */
  w3 /= w4;
  /* #9: @3 = atan(@3) */
  w3 = atan( w3 );
  /* #10: @4 = (@2+@3) */
  w4  = (w2+w3);
  /* #11: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #12: @6 = (@1*@5) */
  w6  = (w1*w5);
  /* #13: @2 = (@2+@3) */
  w2 += w3;
  /* #14: @7 = sin(@2) */
  w7 = sin( w2 );
  /* #15: @8 = (@1*@7) */
  w8  = (w1*w7);
  /* #16: @9 = 1.5 */
  w9 = 1.5000000000000000e+00;
  /* #17: @9 = (@1/@9) */
  w9  = (w1/w9);
  /* #18: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #19: @9 = (@9*@3) */
  w9 *= w3;
  /* #20: @10 = input[2][0] */
  w10 = arg[2] ? arg[2][0] : 0;
  /* #21: @11 = vertcat(@6, @8, @9, @10) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #22: @0 = (@0-@11) */
  for (i=0, rr=w0, cs=w11; i<4; ++i) (*rr++) -= (*cs++);
  /* #23: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #24: @12 = zeros(4x4,5nz) */
  casadi_clear(w12, 5);
  /* #25: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #26: @13 = ones(4x1,3nz) */
  casadi_fill(w13, 3, 1.);
  /* #27: {NULL, NULL, @6, NULL} = vertsplit(@13) */
  w6 = w13[2];
  /* #28: @4 = (@4*@6) */
  w4 *= w6;
  /* #29: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #30: @4 = (-@4) */
  w4 = (- w4 );
  /* #31: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #32: @2 = (@2*@6) */
  w2 *= w6;
  /* #33: @1 = (@1*@2) */
  w1 *= w2;
  /* #34: @14 = 00 */
  /* #35: @15 = 00 */
  /* #36: @16 = vertcat(@4, @1, @14, @15) */
  rr=w16;
  *rr++ = w4;
  *rr++ = w1;
  /* #37: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<2; ++i) *rr++ = (- *cs++ );
  /* #38: @17 = @16[:2] */
  for (rr=w17, ss=w16+0; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #39: (@12[:4:2] = @17) */
  for (rr=w12+0, ss=w17; rr!=w12+4; rr+=2) *rr = *ss++;
  /* #40: @4 = ones(4x1,1nz) */
  w4 = 1.;
  /* #41: {NULL, NULL, NULL, @1} = vertsplit(@4) */
  w1 = w4;
  /* #42: @5 = (@5*@1) */
  w5 *= w1;
  /* #43: @7 = (@7*@1) */
  w7 *= w1;
  /* #44: @4 = 0.666667 */
  w4 = 6.6666666666666663e-01;
  /* #45: @4 = (@4*@1) */
  w4 *= w1;
  /* #46: @3 = (@3*@4) */
  w3 *= w4;
  /* #47: @14 = 00 */
  /* #48: @13 = vertcat(@5, @7, @3, @14) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w3;
  /* #49: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #50: @18 = @13[:3] */
  for (rr=w18, ss=w13+0; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #51: (@12[1, 3, 4] = @18) */
  for (cii=casadi_s0, rr=w12, ss=w18; cii!=casadi_s0+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #52: @19 = @12' */
  casadi_trans(w12,casadi_s2, w19, casadi_s1, iw);
  /* #53: output[1][0] = @19 */
  casadi_copy(w19, 5, res[1]);
  /* #54: @0 = zeros(4x4,4nz) */
  casadi_clear(w0, 4);
  /* #55: @11 = ones(4x1) */
  casadi_fill(w11, 4, 1.);
  /* #56: (@0[:4] = @11) */
  for (rr=w0+0, ss=w11; rr!=w0+4; rr+=1) *rr = *ss++;
  /* #57: @11 = @0' */
  casadi_trans(w0,casadi_s3, w11, casadi_s3, iw);
  /* #58: output[2][0] = @11 */
  casadi_copy(w11, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void race_car_dynamics_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real race_car_dynamics_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* race_car_dynamics_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* race_car_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int race_car_dynamics_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 38;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
