/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Differential_Drive_Dynamic_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[9] = {5, 2, 0, 2, 4, 3, 4, 3, 4};
static const casadi_int casadi_s1[12] = {2, 5, 0, 0, 0, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[11] = {5, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[23] = {5, 5, 0, 3, 6, 9, 12, 15, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* Differential_Drive_Dynamic_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[6])->(o0[5],o1[5x5,15nz],o2[5x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, *w9=w+33, *w10=w+38, *w11=w+43, *w12=w+48, *w13=w+53, w14, w15, w16, w17, w18, *w19=w+63, *w23=w+67, *w24=w+69, *w25=w+71, *w26=w+75, *w27=w+85, *w28=w+95, *w29=w+98, *w30=w+101;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = 0.00265655 */
  w4 = 2.6565535794350619e-03;
  /* #11: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #12: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #13: @7 = (@5+@6) */
  w7  = (w5+w6);
  /* #14: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #15: output[0][3] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #16: @7 = 0.17775 */
  w7 = 1.7774999999999999e-01;
  /* #17: @5 = (@5-@6) */
  w5 -= w6;
  /* #18: @5 = (@7*@5) */
  w5  = (w7*w5);
  /* #19: @6 = 1.1585 */
  w6 = 1.1584956799999999e+00;
  /* #20: @5 = (@5/@6) */
  w5 /= w6;
  /* #21: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #22: @8 = input[1][0] */
  casadi_copy(arg[1], 25, w8);
  /* #23: {@9, @10, @11, @12, @13} = horzsplit(@8) */
  casadi_copy(w8, 5, w9);
  casadi_copy(w8+5, 5, w10);
  casadi_copy(w8+10, 5, w11);
  casadi_copy(w8+15, 5, w12);
  casadi_copy(w8+20, 5, w13);
  /* #24: {NULL, NULL, @5, @6, @14} = vertsplit(@9) */
  w5 = w9[2];
  w6 = w9[3];
  w14 = w9[4];
  /* #25: @15 = (@2*@6) */
  w15  = (w2*w6);
  /* #26: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #27: @17 = (@16*@5) */
  w17  = (w16*w5);
  /* #28: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #29: @15 = (@15-@17) */
  w15 -= w17;
  /* #30: output[1][0] = @15 */
  if (res[1]) res[1][0] = w15;
  /* #31: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #32: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #33: @5 = (@15*@5) */
  w5  = (w15*w5);
  /* #34: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #35: @6 = (@6+@5) */
  w6 += w5;
  /* #36: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #37: output[1][2] = @14 */
  if (res[1]) res[1][2] = w14;
  /* #38: {NULL, NULL, @14, @6, @5} = vertsplit(@10) */
  w14 = w10[2];
  w6 = w10[3];
  w5 = w10[4];
  /* #39: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #40: @18 = (@16*@14) */
  w18  = (w16*w14);
  /* #41: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #42: @17 = (@17-@18) */
  w17 -= w18;
  /* #43: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #44: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #45: @14 = (@15*@14) */
  w14  = (w15*w14);
  /* #46: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #47: @6 = (@6+@14) */
  w6 += w14;
  /* #48: output[1][4] = @6 */
  if (res[1]) res[1][4] = w6;
  /* #49: output[1][5] = @5 */
  if (res[1]) res[1][5] = w5;
  /* #50: {NULL, NULL, @5, @6, @14} = vertsplit(@11) */
  w5 = w11[2];
  w6 = w11[3];
  w14 = w11[4];
  /* #51: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #52: @18 = (@16*@5) */
  w18  = (w16*w5);
  /* #53: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #54: @17 = (@17-@18) */
  w17 -= w18;
  /* #55: output[1][6] = @17 */
  if (res[1]) res[1][6] = w17;
  /* #56: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #57: @5 = (@15*@5) */
  w5  = (w15*w5);
  /* #58: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #59: @6 = (@6+@5) */
  w6 += w5;
  /* #60: output[1][7] = @6 */
  if (res[1]) res[1][7] = w6;
  /* #61: output[1][8] = @14 */
  if (res[1]) res[1][8] = w14;
  /* #62: {NULL, NULL, @14, @6, @5} = vertsplit(@12) */
  w14 = w12[2];
  w6 = w12[3];
  w5 = w12[4];
  /* #63: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #64: @18 = (@16*@14) */
  w18  = (w16*w14);
  /* #65: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #66: @17 = (@17-@18) */
  w17 -= w18;
  /* #67: output[1][9] = @17 */
  if (res[1]) res[1][9] = w17;
  /* #68: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #69: @14 = (@15*@14) */
  w14  = (w15*w14);
  /* #70: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #71: @6 = (@6+@14) */
  w6 += w14;
  /* #72: output[1][10] = @6 */
  if (res[1]) res[1][10] = w6;
  /* #73: output[1][11] = @5 */
  if (res[1]) res[1][11] = w5;
  /* #74: {NULL, NULL, @5, @6, @14} = vertsplit(@13) */
  w5 = w13[2];
  w6 = w13[3];
  w14 = w13[4];
  /* #75: @17 = (@2*@6) */
  w17  = (w2*w6);
  /* #76: @16 = (@16*@5) */
  w16 *= w5;
  /* #77: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #78: @17 = (@17-@16) */
  w17 -= w16;
  /* #79: output[1][12] = @17 */
  if (res[1]) res[1][12] = w17;
  /* #80: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #81: @15 = (@15*@5) */
  w15 *= w5;
  /* #82: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #83: @6 = (@6+@15) */
  w6 += w15;
  /* #84: output[1][13] = @6 */
  if (res[1]) res[1][13] = w6;
  /* #85: output[1][14] = @14 */
  if (res[1]) res[1][14] = w14;
  /* #86: @19 = zeros(2x5,4nz) */
  casadi_clear(w19, 4);
  /* #87: @20 = 00 */
  /* #88: @21 = 00 */
  /* #89: @22 = 00 */
  /* #90: @14 = ones(2x1,1nz) */
  w14 = 1.;
  /* #91: {@6, NULL} = vertsplit(@14) */
  w6 = w14;
  /* #92: @14 = (@4*@6) */
  w14  = (w4*w6);
  /* #93: @15 = 0.863188 */
  w15 = 8.6318837201015719e-01;
  /* #94: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #95: @6 = (@15*@6) */
  w6  = (w15*w6);
  /* #96: @23 = vertcat(@20, @21, @22, @14, @6) */
  rr=w23;
  *rr++ = w14;
  *rr++ = w6;
  /* #97: @24 = @23[:2] */
  for (rr=w24, ss=w23+0; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #98: (@19[:4:2] = @24) */
  for (rr=w19+0, ss=w24; rr!=w19+4; rr+=2) *rr = *ss++;
  /* #99: @20 = 00 */
  /* #100: @21 = 00 */
  /* #101: @22 = 00 */
  /* #102: @14 = ones(2x1,1nz) */
  w14 = 1.;
  /* #103: {NULL, @6} = vertsplit(@14) */
  w6 = w14;
  /* #104: @4 = (@4*@6) */
  w4 *= w6;
  /* #105: @7 = (@7*@6) */
  w7 *= w6;
  /* #106: @15 = (@15*@7) */
  w15 *= w7;
  /* #107: @15 = (-@15) */
  w15 = (- w15 );
  /* #108: @24 = vertcat(@20, @21, @22, @4, @15) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w15;
  /* #109: @23 = @24[:2] */
  for (rr=w23, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #110: (@19[1:5:2] = @23) */
  for (rr=w19+1, ss=w23; rr!=w19+5; rr+=2) *rr = *ss++;
  /* #111: @25 = @19' */
  casadi_trans(w19,casadi_s1, w25, casadi_s0, iw);
  /* #112: @26 = dense(@25) */
  casadi_densify(w25, casadi_s0, w26, 0);
  /* #113: @27 = input[2][0] */
  casadi_copy(arg[2], 10, w27);
  /* #114: {@13, @12} = horzsplit(@27) */
  casadi_copy(w27, 5, w13);
  casadi_copy(w27+5, 5, w12);
  /* #115: {NULL, NULL, @4, @15, @7} = vertsplit(@13) */
  w4 = w13[2];
  w15 = w13[3];
  w7 = w13[4];
  /* #116: @6 = (@2*@15) */
  w6  = (w2*w15);
  /* #117: @14 = sin(@1) */
  w14 = sin( w1 );
  /* #118: @5 = (@14*@4) */
  w5  = (w14*w4);
  /* #119: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #120: @6 = (@6-@5) */
  w6 -= w5;
  /* #121: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #122: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #123: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #124: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #125: @15 = (@15+@4) */
  w15 += w4;
  /* #126: @20 = 00 */
  /* #127: @21 = 00 */
  /* #128: @28 = vertcat(@6, @15, @7, @20, @21) */
  rr=w28;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w7;
  /* #129: {NULL, NULL, @6, @15, @7} = vertsplit(@12) */
  w6 = w12[2];
  w15 = w12[3];
  w7 = w12[4];
  /* #130: @2 = (@2*@15) */
  w2 *= w15;
  /* #131: @14 = (@14*@6) */
  w14 *= w6;
  /* #132: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #133: @2 = (@2-@14) */
  w2 -= w14;
  /* #134: @3 = (@3*@15) */
  w3 *= w15;
  /* #135: @1 = (@1*@6) */
  w1 *= w6;
  /* #136: @0 = (@0*@1) */
  w0 *= w1;
  /* #137: @3 = (@3+@0) */
  w3 += w0;
  /* #138: @20 = 00 */
  /* #139: @21 = 00 */
  /* #140: @29 = vertcat(@2, @3, @7, @20, @21) */
  rr=w29;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  /* #141: @30 = horzcat(@28, @29) */
  rr=w30;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #142: @27 = dense(@30) */
  casadi_densify(w30, casadi_s2, w27, 0);
  /* #143: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<10; ++i) (*rr++) += (*cs++);
  /* #144: output[2][0] = @26 */
  casadi_copy(w26, 10, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Dynamic_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Dynamic_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Differential_Drive_Dynamic_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Dynamic_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Dynamic_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Dynamic_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Dynamic_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s8;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 107;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
