/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = {5, 5, 0, 0, 0, 2, 4, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s1[13] = {5, 5, 0, 2, 4, 5, 5, 5, 2, 3, 2, 3, 4};
static const casadi_int casadi_s2[13] = {5, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s7[3] = {5, 0, 0};

/* four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z:(i0[5],i1[5],i2[4],i3[],i4[],i5[9])->(o0[5],o1[5x5,5nz],o2[5x5,5nz],o3[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+18, *w15=w+23, *w18=w+27, *w19=w+30, *w21=w+33, *w22=w+35;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 5, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #5: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #6: @6 = (@1*@5) */
  w6  = (w1*w5);
  /* #7: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = 0.0017775 */
  w8 = 1.7775000000000000e-03;
  /* #9: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #10: @10 = input[2][1] */
  w10 = arg[2] ? arg[2][1] : 0;
  /* #11: @11 = (@9+@10) */
  w11  = (w9+w10);
  /* #12: @12 = input[2][2] */
  w12 = arg[2] ? arg[2][2] : 0;
  /* #13: @11 = (@11+@12) */
  w11 += w12;
  /* #14: @13 = input[2][3] */
  w13 = arg[2] ? arg[2][3] : 0;
  /* #15: @11 = (@11+@13) */
  w11 += w13;
  /* #16: @8 = (@8*@11) */
  w8 *= w11;
  /* #17: @11 = 0.302452 */
  w11 = 3.0245245294299250e-01;
  /* #18: @9 = (@9+@12) */
  w9 += w12;
  /* #19: @10 = (@10+@13) */
  w10 += w13;
  /* #20: @9 = (@9-@10) */
  w9 -= w10;
  /* #21: @11 = (@11*@9) */
  w11 *= w9;
  /* #22: @9 = 2 */
  w9 = 2.;
  /* #23: @11 = (@11/@9) */
  w11 /= w9;
  /* #24: @14 = vertcat(@4, @6, @7, @8, @11) */
  rr=w14;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w11;
  /* #25: @0 = (@0-@14) */
  for (i=0, rr=w0, cs=w14; i<5; ++i) (*rr++) -= (*cs++);
  /* #26: output[0][0] = @0 */
  casadi_copy(w0, 5, res[0]);
  /* #27: @0 = zeros(5x5,5nz) */
  casadi_clear(w0, 5);
  /* #28: @4 = sin(@2) */
  w4 = sin( w2 );
  /* #29: @15 = ones(5x1,4nz) */
  casadi_fill(w15, 4, 1.);
  /* #30: {NULL, NULL, @6, NULL, @7} = vertsplit(@15) */
  w6 = w15[2];
  w7 = w15[3];
  /* #31: @4 = (@4*@6) */
  w4 *= w6;
  /* #32: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #33: @4 = (-@4) */
  w4 = (- w4 );
  /* #34: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #35: @2 = (@2*@6) */
  w2 *= w6;
  /* #36: @1 = (@1*@2) */
  w1 *= w2;
  /* #37: @16 = 00 */
  /* #38: @17 = 00 */
  /* #39: @18 = vertcat(@4, @1, @7, @16, @17) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w7;
  /* #40: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #41: @19 = @18[:3] */
  for (rr=w19, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #42: (@0[:6:2] = @19) */
  for (rr=w0+0, ss=w19; rr!=w0+6; rr+=2) *rr = *ss++;
  /* #43: @4 = ones(5x1,1nz) */
  w4 = 1.;
  /* #44: {NULL, NULL, NULL, @1, NULL} = vertsplit(@4) */
  w1 = w4;
  /* #45: @3 = (@3*@1) */
  w3 *= w1;
  /* #46: @5 = (@5*@1) */
  w5 *= w1;
  /* #47: @16 = 00 */
  /* #48: @17 = 00 */
  /* #49: @20 = 00 */
  /* #50: @21 = vertcat(@3, @5, @16, @17, @20) */
  rr=w21;
  *rr++ = w3;
  *rr++ = w5;
  /* #51: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<2; ++i) *rr++ = (- *cs++ );
  /* #52: @22 = @21[:2] */
  for (rr=w22, ss=w21+0; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #53: (@0[1:5:2] = @22) */
  for (rr=w0+1, ss=w22; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #54: @14 = @0' */
  casadi_trans(w0,casadi_s1, w14, casadi_s0, iw);
  /* #55: output[1][0] = @14 */
  casadi_copy(w14, 5, res[1]);
  /* #56: @14 = zeros(5x5,5nz) */
  casadi_clear(w14, 5);
  /* #57: @0 = ones(5x1) */
  casadi_fill(w0, 5, 1.);
  /* #58: (@14[:5] = @0) */
  for (rr=w14+0, ss=w0; rr!=w14+5; rr+=1) *rr = *ss++;
  /* #59: @0 = @14' */
  casadi_trans(w14,casadi_s2, w0, casadi_s2, iw);
  /* #60: output[2][0] = @0 */
  casadi_copy(w0, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 37;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
