/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) four_wheel_drive_dynamics_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* four_wheel_drive_dynamics_impl_dae_fun:(i0[5],i1[5],i2[4],i3[],i4[],i5[9])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+14;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 5, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #6: @1 = (@1*@2) */
  w1 *= w2;
  /* #7: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #8: @4 = 0.0017775 */
  w4 = 1.7775000000000000e-03;
  /* #9: @5 = input[2][0] */
  w5 = arg[2] ? arg[2][0] : 0;
  /* #10: @6 = input[2][1] */
  w6 = arg[2] ? arg[2][1] : 0;
  /* #11: @7 = (@5+@6) */
  w7  = (w5+w6);
  /* #12: @8 = input[2][2] */
  w8 = arg[2] ? arg[2][2] : 0;
  /* #13: @7 = (@7+@8) */
  w7 += w8;
  /* #14: @9 = input[2][3] */
  w9 = arg[2] ? arg[2][3] : 0;
  /* #15: @7 = (@7+@9) */
  w7 += w9;
  /* #16: @4 = (@4*@7) */
  w4 *= w7;
  /* #17: @7 = 0.302452 */
  w7 = 3.0245245294299250e-01;
  /* #18: @5 = (@5+@8) */
  w5 += w8;
  /* #19: @6 = (@6+@9) */
  w6 += w9;
  /* #20: @5 = (@5-@6) */
  w5 -= w6;
  /* #21: @7 = (@7*@5) */
  w7 *= w5;
  /* #22: @5 = 2 */
  w5 = 2.;
  /* #23: @7 = (@7/@5) */
  w7 /= w5;
  /* #24: @10 = vertcat(@3, @1, @2, @4, @7) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w7;
  /* #25: @0 = (@0-@10) */
  for (i=0, rr=w0, cs=w10; i<5; ++i) (*rr++) -= (*cs++);
  /* #26: output[0][0] = @0 */
  casadi_copy(w0, 5, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real four_wheel_drive_dynamics_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
