/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {5, 5, 0, 0, 0, 2, 4, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s1[13] = {5, 5, 0, 2, 4, 5, 5, 5, 2, 3, 2, 3, 4};
static const casadi_int casadi_s2[13] = {5, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[15] = {5, 4, 0, 2, 4, 6, 8, 3, 4, 3, 4, 3, 4, 3, 4};
static const casadi_int casadi_s4[16] = {4, 5, 0, 0, 0, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s5[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s9[3] = {5, 0, 0};

/* four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z:(i0[5],i1[5],i2[4],i3[],i4[],i5[9])->(o0[5x5,5nz],o1[5x5,5nz],o2[5x4,8nz],o3[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, *w4=w+8, w5, w6, w7, *w10=w+15, *w11=w+18, *w13=w+21, *w14=w+23, *w15=w+25, *w16=w+30, *w17=w+38;
  /* #0: @0 = zeros(5x5,5nz) */
  casadi_clear(w0, 5);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = ones(5x1,4nz) */
  casadi_fill(w4, 4, 1.);
  /* #5: {NULL, NULL, @5, NULL, @6} = vertsplit(@4) */
  w5 = w4[2];
  w6 = w4[3];
  /* #6: @3 = (@3*@5) */
  w3 *= w5;
  /* #7: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #8: @3 = (-@3) */
  w3 = (- w3 );
  /* #9: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #10: @7 = (@7*@5) */
  w7 *= w5;
  /* #11: @1 = (@1*@7) */
  w1 *= w7;
  /* #12: @8 = 00 */
  /* #13: @9 = 00 */
  /* #14: @10 = vertcat(@3, @1, @6, @8, @9) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w1;
  *rr++ = w6;
  /* #15: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (- *cs++ );
  /* #16: @11 = @10[:3] */
  for (rr=w11, ss=w10+0; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #17: (@0[:6:2] = @11) */
  for (rr=w0+0, ss=w11; rr!=w0+6; rr+=2) *rr = *ss++;
  /* #18: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #19: @1 = ones(5x1,1nz) */
  w1 = 1.;
  /* #20: {NULL, NULL, NULL, @6, NULL} = vertsplit(@1) */
  w6 = w1;
  /* #21: @3 = (@3*@6) */
  w3 *= w6;
  /* #22: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #23: @2 = (@2*@6) */
  w2 *= w6;
  /* #24: @8 = 00 */
  /* #25: @9 = 00 */
  /* #26: @12 = 00 */
  /* #27: @13 = vertcat(@3, @2, @8, @9, @12) */
  rr=w13;
  *rr++ = w3;
  *rr++ = w2;
  /* #28: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<2; ++i) *rr++ = (- *cs++ );
  /* #29: @14 = @13[:2] */
  for (rr=w14, ss=w13+0; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #30: (@0[1:5:2] = @14) */
  for (rr=w0+1, ss=w14; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #31: @15 = @0' */
  casadi_trans(w0,casadi_s1, w15, casadi_s0, iw);
  /* #32: output[0][0] = @15 */
  casadi_copy(w15, 5, res[0]);
  /* #33: @15 = zeros(5x5,5nz) */
  casadi_clear(w15, 5);
  /* #34: @0 = ones(5x1) */
  casadi_fill(w0, 5, 1.);
  /* #35: (@15[:5] = @0) */
  for (rr=w15+0, ss=w0; rr!=w15+5; rr+=1) *rr = *ss++;
  /* #36: @0 = @15' */
  casadi_trans(w15,casadi_s2, w0, casadi_s2, iw);
  /* #37: output[1][0] = @0 */
  casadi_copy(w0, 5, res[1]);
  /* #38: @16 = zeros(4x5,8nz) */
  casadi_clear(w16, 8);
  /* #39: @8 = 00 */
  /* #40: @9 = 00 */
  /* #41: @12 = 00 */
  /* #42: @3 = 0.0017775 */
  w3 = 1.7775000000000000e-03;
  /* #43: @2 = ones(4x1,1nz) */
  w2 = 1.;
  /* #44: {@6, NULL, NULL, NULL} = vertsplit(@2) */
  w6 = w2;
  /* #45: @2 = (@3*@6) */
  w2  = (w3*w6);
  /* #46: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #47: @7 = 0.302452 */
  w7 = 3.0245245294299250e-01;
  /* #48: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #49: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #50: @14 = vertcat(@8, @9, @12, @2, @6) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w6;
  /* #51: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<2; ++i) *rr++ = (- *cs++ );
  /* #52: @13 = @14[:2] */
  for (rr=w13, ss=w14+0; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #53: (@16[:8:4] = @13) */
  for (rr=w16+0, ss=w13; rr!=w16+8; rr+=4) *rr = *ss++;
  /* #54: @8 = 00 */
  /* #55: @9 = 00 */
  /* #56: @12 = 00 */
  /* #57: @2 = ones(4x1,1nz) */
  w2 = 1.;
  /* #58: {NULL, @6, NULL, NULL} = vertsplit(@2) */
  w6 = w2;
  /* #59: @2 = (@3*@6) */
  w2  = (w3*w6);
  /* #60: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #61: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #62: @6 = (-@6) */
  w6 = (- w6 );
  /* #63: @13 = vertcat(@8, @9, @12, @2, @6) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w6;
  /* #64: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<2; ++i) *rr++ = (- *cs++ );
  /* #65: @14 = @13[:2] */
  for (rr=w14, ss=w13+0; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #66: (@16[1:9:4] = @14) */
  for (rr=w16+1, ss=w14; rr!=w16+9; rr+=4) *rr = *ss++;
  /* #67: @8 = 00 */
  /* #68: @9 = 00 */
  /* #69: @12 = 00 */
  /* #70: @2 = ones(4x1,1nz) */
  w2 = 1.;
  /* #71: {NULL, NULL, @6, NULL} = vertsplit(@2) */
  w6 = w2;
  /* #72: @2 = (@3*@6) */
  w2  = (w3*w6);
  /* #73: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #74: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #75: @14 = vertcat(@8, @9, @12, @2, @6) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w6;
  /* #76: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<2; ++i) *rr++ = (- *cs++ );
  /* #77: @13 = @14[:2] */
  for (rr=w13, ss=w14+0; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #78: (@16[2:10:4] = @13) */
  for (rr=w16+2, ss=w13; rr!=w16+10; rr+=4) *rr = *ss++;
  /* #79: @8 = 00 */
  /* #80: @9 = 00 */
  /* #81: @12 = 00 */
  /* #82: @2 = ones(4x1,1nz) */
  w2 = 1.;
  /* #83: {NULL, NULL, NULL, @6} = vertsplit(@2) */
  w6 = w2;
  /* #84: @3 = (@3*@6) */
  w3 *= w6;
  /* #85: @7 = (@7*@6) */
  w7 *= w6;
  /* #86: @1 = (@1*@7) */
  w1 *= w7;
  /* #87: @1 = (-@1) */
  w1 = (- w1 );
  /* #88: @13 = vertcat(@8, @9, @12, @3, @1) */
  rr=w13;
  *rr++ = w3;
  *rr++ = w1;
  /* #89: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<2; ++i) *rr++ = (- *cs++ );
  /* #90: @14 = @13[:2] */
  for (rr=w14, ss=w13+0; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #91: (@16[3:11:4] = @14) */
  for (rr=w16+3, ss=w14; rr!=w16+11; rr+=4) *rr = *ss++;
  /* #92: @17 = @16' */
  casadi_trans(w16,casadi_s4, w17, casadi_s3, iw);
  /* #93: output[2][0] = @17 */
  casadi_copy(w17, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    case 5: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 46;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
