/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[12] = {7, 3, 0, 2, 4, 6, 2, 3, 2, 3, 2, 3};
static const casadi_int casadi_s6[3] = {3, 0, 0};

/* Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt:(i0[5],i1[2],i2[],i3[6])->(o0[3],o1[7x3,6nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5, w6, w7, w8, *w9=w+14, *w10=w+20;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[3][0] */
  casadi_copy(arg[3], 6, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @2 = (@0-@2) */
  w2  = (w0-w2);
  /* #4: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #5: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #6: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @5 = (@4-@5) */
  w5  = (w4-w5);
  /* #8: @6 = sq(@5) */
  w6 = casadi_sq( w5 );
  /* #9: @3 = (@3+@6) */
  w3 += w6;
  /* #10: @6 = 0.49 */
  w6 = 4.8999999999999994e-01;
  /* #11: @3 = (@3-@6) */
  w3 -= w6;
  /* #12: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #13: @3 = @1[2] */
  for (rr=(&w3), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #14: @3 = (@0-@3) */
  w3  = (w0-w3);
  /* #15: @6 = sq(@3) */
  w6 = casadi_sq( w3 );
  /* #16: @7 = @1[3] */
  for (rr=(&w7), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #17: @7 = (@4-@7) */
  w7  = (w4-w7);
  /* #18: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #19: @6 = (@6+@8) */
  w6 += w8;
  /* #20: @8 = 0.25 */
  w8 = 2.5000000000000000e-01;
  /* #21: @6 = (@6-@8) */
  w6 -= w8;
  /* #22: output[0][1] = @6 */
  if (res[0]) res[0][1] = w6;
  /* #23: @6 = @1[4] */
  for (rr=(&w6), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #24: @0 = (@0-@6) */
  w0 -= w6;
  /* #25: @6 = sq(@0) */
  w6 = casadi_sq( w0 );
  /* #26: @8 = @1[5] */
  for (rr=(&w8), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #27: @4 = (@4-@8) */
  w4 -= w8;
  /* #28: @8 = sq(@4) */
  w8 = casadi_sq( w4 );
  /* #29: @6 = (@6+@8) */
  w6 += w8;
  /* #30: @8 = 0.36 */
  w8 = 3.6000000000000010e-01;
  /* #31: @6 = (@6-@8) */
  w6 -= w8;
  /* #32: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #33: @1 = zeros(7x3,6nz) */
  casadi_clear(w1, 6);
  /* #34: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #35: @9 = ones(7x1,6nz) */
  casadi_fill(w9, 6, 1.);
  /* #36: {NULL, NULL, @6, NULL, NULL, NULL, NULL} = vertsplit(@9) */
  w6 = w9[2];
  /* #37: @2 = (@2*@6) */
  w2 *= w6;
  /* #38: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #39: @3 = (@3*@6) */
  w3 *= w6;
  /* #40: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #41: @0 = (@0*@6) */
  w0 *= w6;
  /* #42: @10 = vertcat(@2, @3, @0) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w0;
  /* #43: (@1[:6:2] = @10) */
  for (rr=w1+0, ss=w10; rr!=w1+6; rr+=2) *rr = *ss++;
  /* #44: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #45: @2 = ones(7x1,1nz) */
  w2 = 1.;
  /* #46: {NULL, NULL, NULL, @3, NULL, NULL, NULL} = vertsplit(@2) */
  w3 = w2;
  /* #47: @5 = (@5*@3) */
  w5 *= w3;
  /* #48: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #49: @7 = (@7*@3) */
  w7 *= w3;
  /* #50: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #51: @4 = (@4*@3) */
  w4 *= w3;
  /* #52: @10 = vertcat(@5, @7, @4) */
  rr=w10;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #53: (@1[1:7:2] = @10) */
  for (rr=w1+1, ss=w10; rr!=w1+7; rr+=2) *rr = *ss++;
  /* #54: output[1][0] = @1 */
  casadi_copy(w1, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Dynamic_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
