/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[3] = {0, 0, 0};

/* External functions */
int jac_learned_dyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int learned_dyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* learned_dyn:(i0[2])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (learned_dyn(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_learned_dyn:(i0[2],out_o0[1x1,0nz])->(jac_o0_i0[1x2]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_learned_dyn(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* wr_expl_vde_forw:(i0[2],i1[2x2],i2[2],i3,i4[])->(o0[2],o1[2x2],o2[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+3, *rr, *ss, *tt;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, *w2=w+3, *w3=w+5, *w4=w+7, *w5=w+11, *w7=w+13, *w8=w+15, w9;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = vertcat(@0, @1) */
  rr=w2;
  *rr++ = w0;
  *rr++ = w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @3 = vertcat(@1, @0) */
  rr=w3;
  *rr++ = w1;
  *rr++ = w0;
  /* #5: @1 = learned_dyn(@3) */
  arg1[0]=w3;
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: @2 = (@2+@1) */
  for (i=0, rr=w2; i<2; ++i) (*rr++) += w1;
  /* #7: output[0][0] = @2 */
  casadi_copy(w2, 2, res[0]);
  /* #8: @4 = input[1][0] */
  casadi_copy(arg[1], 4, w4);
  /* #9: {@2, @5} = horzsplit(@4) */
  casadi_copy(w4, 2, w2);
  casadi_copy(w4+2, 2, w5);
  /* #10: {NULL, @1} = vertsplit(@2) */
  w1 = w2[1];
  /* #11: @6 = 00 */
  /* #12: @0 = vertcat(@1, @6) */
  rr=(&w0);
  *rr++ = w1;
  /* #13: @2 = dense(@0) */
  casadi_densify((&w0), casadi_s0, w2, 0);
  /* #14: @7 = zeros(1x2) */
  casadi_clear(w7, 2);
  /* #15: @6 = 00 */
  /* #16: @8 = jac_learned_dyn(@3, @6) */
  arg1[0]=w3;
  arg1[1]=0;
  res1[0]=w8;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @7 = mac(@8,@4,@7) */
  for (i=0, rr=w7; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #18: {@0, @1} = horzsplit(@7) */
  w0 = w7[0];
  w1 = w7[1];
  /* #19: @2 = (@2+@0) */
  for (i=0, rr=w2; i<2; ++i) (*rr++) += w0;
  /* #20: output[1][0] = @2 */
  casadi_copy(w2, 2, res[1]);
  /* #21: {NULL, @0} = vertsplit(@5) */
  w0 = w5[1];
  /* #22: @6 = 00 */
  /* #23: @9 = vertcat(@0, @6) */
  rr=(&w9);
  *rr++ = w0;
  /* #24: @5 = dense(@9) */
  casadi_densify((&w9), casadi_s0, w5, 0);
  /* #25: @5 = (@5+@1) */
  for (i=0, rr=w5; i<2; ++i) (*rr++) += w1;
  /* #26: output[1][1] = @5 */
  if (res[1]) casadi_copy(w5, 2, res[1]+2);
  /* #27: @1 = zeros(1x2,1nz) */
  w1 = 0.;
  /* #28: @9 = 1 */
  w9 = 1.;
  /* #29: (@1[0] = @9) */
  for (rr=(&w1)+0, ss=(&w9); rr!=(&w1)+1; rr+=1) *rr = *ss++;
  /* #30: @1 = @1' */
  /* #31: @5 = dense(@1) */
  casadi_densify((&w1), casadi_s1, w5, 0);
  /* #32: @2 = input[2][0] */
  casadi_copy(arg[2], 2, w2);
  /* #33: {NULL, @1} = vertsplit(@2) */
  w1 = w2[1];
  /* #34: @6 = 00 */
  /* #35: @9 = vertcat(@1, @6) */
  rr=(&w9);
  *rr++ = w1;
  /* #36: @7 = dense(@9) */
  casadi_densify((&w9), casadi_s0, w7, 0);
  /* #37: @9 = 0 */
  w9 = 0.;
  /* #38: @6 = 00 */
  /* #39: @8 = jac_learned_dyn(@3, @6) */
  arg1[0]=w3;
  arg1[1]=0;
  res1[0]=w8;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: @9 = mac(@8,@2,@9) */
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: @7 = (@7+@9) */
  for (i=0, rr=w7; i<2; ++i) (*rr++) += w9;
  /* #42: @5 = (@5+@7) */
  for (i=0, rr=w5, cs=w7; i<2; ++i) (*rr++) += (*cs++);
  /* #43: output[2][0] = @5 */
  casadi_copy(w5, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wr_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 18;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
