/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Differential_Drive_Static_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[8] = {3, 2, 0, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {2, 3, 0, 1, 2, 3, 0, 0, 1};
static const casadi_int casadi_s2[10] = {3, 2, 0, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s3[9] = {3, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s9[12] = {3, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};

/* Differential_Drive_Static_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4[12])->(o0[3],o1[3x3,6nz],o2[3x2,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+8, *w6=w+17, *w7=w+20, *w8=w+23, w9, w10, w11, *w12=w+29, *w13=w+31, *w14=w+36, *w16=w+42, *w17=w+44, *w18=w+48;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #11: @5 = input[1][0] */
  casadi_copy(arg[1], 9, w5);
  /* #12: {@6, @7, @8} = horzsplit(@5) */
  casadi_copy(w5, 3, w6);
  casadi_copy(w5+3, 3, w7);
  casadi_copy(w5+6, 3, w8);
  /* #13: {NULL, NULL, @9} = vertsplit(@6) */
  w9 = w6[2];
  /* #14: @10 = (@4*@9) */
  w10  = (w4*w9);
  /* #15: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #16: @10 = (-@10) */
  w10 = (- w10 );
  /* #17: output[1][0] = @10 */
  if (res[1]) res[1][0] = w10;
  /* #18: @10 = cos(@1) */
  w10 = cos( w1 );
  /* #19: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #20: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #21: output[1][1] = @9 */
  if (res[1]) res[1][1] = w9;
  /* #22: {NULL, NULL, @9} = vertsplit(@7) */
  w9 = w7[2];
  /* #23: @11 = (@4*@9) */
  w11  = (w4*w9);
  /* #24: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #25: @11 = (-@11) */
  w11 = (- w11 );
  /* #26: output[1][2] = @11 */
  if (res[1]) res[1][2] = w11;
  /* #27: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #28: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #29: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #30: {NULL, NULL, @9} = vertsplit(@8) */
  w9 = w8[2];
  /* #31: @4 = (@4*@9) */
  w4 *= w9;
  /* #32: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #33: @4 = (-@4) */
  w4 = (- w4 );
  /* #34: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #35: @10 = (@10*@9) */
  w10 *= w9;
  /* #36: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #37: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #38: @8 = zeros(2x3,3nz) */
  casadi_clear(w8, 3);
  /* #39: @12 = ones(2x1) */
  casadi_fill(w12, 2, 1.);
  /* #40: {@10, @9} = vertsplit(@12) */
  w10 = w12[0];
  w9 = w12[1];
  /* #41: @2 = (@2*@10) */
  w2 *= w10;
  /* #42: @3 = (@3*@10) */
  w3 *= w10;
  /* #43: @7 = vertcat(@2, @3, @9) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w9;
  /* #44: (@8[:3] = @7) */
  for (rr=w8+0, ss=w7; rr!=w8+3; rr+=1) *rr = *ss++;
  /* #45: @7 = @8' */
  casadi_trans(w8,casadi_s1, w7, casadi_s0, iw);
  /* #46: @13 = project(@7) */
  casadi_project(w7, casadi_s0, w13, casadi_s2, w);
  /* #47: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #48: @14 = input[2][0] */
  casadi_copy(arg[2], 6, w14);
  /* #49: {@7, @8} = horzsplit(@14) */
  casadi_copy(w14, 3, w7);
  casadi_copy(w14+3, 3, w8);
  /* #50: {NULL, NULL, @3} = vertsplit(@7) */
  w3 = w7[2];
  /* #51: @9 = (@2*@3) */
  w9  = (w2*w3);
  /* #52: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #53: @9 = (-@9) */
  w9 = (- w9 );
  /* #54: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #55: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #56: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #57: @15 = 00 */
  /* #58: @12 = vertcat(@9, @3, @15) */
  rr=w12;
  *rr++ = w9;
  *rr++ = w3;
  /* #59: {NULL, NULL, @9} = vertsplit(@8) */
  w9 = w8[2];
  /* #60: @2 = (@2*@9) */
  w2 *= w9;
  /* #61: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #62: @2 = (-@2) */
  w2 = (- w2 );
  /* #63: @1 = (@1*@9) */
  w1 *= w9;
  /* #64: @0 = (@0*@1) */
  w0 *= w1;
  /* #65: @15 = 00 */
  /* #66: @16 = vertcat(@2, @0, @15) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w0;
  /* #67: @17 = horzcat(@12, @16) */
  rr=w17;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<2; ++i) *rr++ = *cs++;
  /* #68: @18 = project(@17) */
  casadi_project(w17, casadi_s3, w18, casadi_s2, w);
  /* #69: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<5; ++i) (*rr++) += (*cs++);
  /* #70: output[2][0] = @13 */
  casadi_copy(w13, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Static_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Static_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Static_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Static_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Static_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Static_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Static_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Differential_Drive_Static_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Static_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Differential_Drive_Static_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Differential_Drive_Static_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Static_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Differential_Drive_Static_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Static_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Differential_Drive_Static_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Differential_Drive_Static_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 53;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
