/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) differential_drive_dnn_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[6] = {3, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[15] = {5, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[23] = {3, 5, 0, 3, 6, 9, 12, 15, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {5, 2, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s7[11] = {5, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s10[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* External functions */
int jac_learned_dynamics_differential_drive(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int learned_dynamics_differential_drive(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* learned_dynamics_differential_drive:(i0[5])->(o0[3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (learned_dynamics_differential_drive(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_learned_dynamics_differential_drive:(i0[5],out_o0[3x1,0nz])->(jac_o0_i0[3x5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_learned_dynamics_differential_drive(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* differential_drive_dnn_mpc_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4[12])->(o0[3],o1[3x3],o2[3x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, *w7=w+10, *w8=w+13, *w9=w+18, *w10=w+21, *w11=w+30, w12, w13, w14, w15, *w17=w+37, *w18=w+39, *w20=w+54, *w21=w+57, *w22=w+66, *w23=w+72, *w26=w+78;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #5: @5 = (@0*@4) */
  w5  = (w0*w4);
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = vertcat(@3, @5, @6) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w6;
  /* #8: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #9: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #10: @8 = vertcat(@3, @5, @1, @0, @6) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w0;
  *rr++ = w6;
  /* #11: @9 = learned_dynamics_differential_drive(@8) */
  arg1[0]=w8;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #13: output[0][0] = @7 */
  casadi_copy(w7, 3, res[0]);
  /* #14: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #15: @10 = input[1][0] */
  casadi_copy(arg[1], 9, w10);
  /* #16: {@7, @9, @11} = horzsplit(@10) */
  casadi_copy(w10, 3, w7);
  casadi_copy(w10+3, 3, w9);
  casadi_copy(w10+6, 3, w11);
  /* #17: {@5, @6, @12} = vertsplit(@7) */
  w5 = w7[0];
  w6 = w7[1];
  w12 = w7[2];
  /* #18: @13 = (@3*@12) */
  w13  = (w3*w12);
  /* #19: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #20: @13 = (-@13) */
  w13 = (- w13 );
  /* #21: @14 = cos(@1) */
  w14 = cos( w1 );
  /* #22: @15 = (@14*@12) */
  w15  = (w14*w12);
  /* #23: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #24: @16 = 00 */
  /* #25: @17 = vertcat(@13, @15, @16) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w15;
  /* #26: @7 = dense(@17) */
  casadi_densify(w17, casadi_s0, w7, 0);
  /* #27: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #28: @16 = zeros(3x1,0nz) */
  /* #29: @18 = jac_learned_dynamics_differential_drive(@8, @16) */
  arg1[0]=w8;
  arg1[1]=0;
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #30: @16 = 00 */
  /* #31: @19 = 00 */
  /* #32: @20 = vertcat(@5, @6, @12, @16, @19) */
  rr=w20;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w12;
  /* #33: {@5, @6, @12} = vertsplit(@9) */
  w5 = w9[0];
  w6 = w9[1];
  w12 = w9[2];
  /* #34: @16 = 00 */
  /* #35: @19 = 00 */
  /* #36: @9 = vertcat(@5, @6, @12, @16, @19) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w12;
  /* #37: {@5, @6, @13} = vertsplit(@11) */
  w5 = w11[0];
  w6 = w11[1];
  w13 = w11[2];
  /* #38: @16 = 00 */
  /* #39: @19 = 00 */
  /* #40: @11 = vertcat(@5, @6, @13, @16, @19) */
  rr=w11;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w13;
  /* #41: @21 = horzcat(@20, @9, @11) */
  rr=w21;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  /* #42: @10 = mac(@18,@21,@10) */
  casadi_mtimes(w18, casadi_s3, w21, casadi_s2, w10, casadi_s1, w, 0);
  /* #43: {@20, @9, @11} = horzsplit(@10) */
  casadi_copy(w10, 3, w20);
  casadi_copy(w10+3, 3, w9);
  casadi_copy(w10+6, 3, w11);
  /* #44: @7 = (@7+@20) */
  for (i=0, rr=w7, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #45: output[1][0] = @7 */
  casadi_copy(w7, 3, res[1]);
  /* #46: @5 = (@3*@12) */
  w5  = (w3*w12);
  /* #47: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #48: @5 = (-@5) */
  w5 = (- w5 );
  /* #49: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #50: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #51: @16 = 00 */
  /* #52: @17 = vertcat(@5, @12, @16) */
  rr=w17;
  *rr++ = w5;
  *rr++ = w12;
  /* #53: @7 = dense(@17) */
  casadi_densify(w17, casadi_s0, w7, 0);
  /* #54: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #55: output[1][1] = @7 */
  if (res[1]) casadi_copy(w7, 3, res[1]+3);
  /* #56: @3 = (@3*@13) */
  w3 *= w13;
  /* #57: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #58: @3 = (-@3) */
  w3 = (- w3 );
  /* #59: @14 = (@14*@13) */
  w14 *= w13;
  /* #60: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #61: @16 = 00 */
  /* #62: @17 = vertcat(@3, @14, @16) */
  rr=w17;
  *rr++ = w3;
  *rr++ = w14;
  /* #63: @7 = dense(@17) */
  casadi_densify(w17, casadi_s0, w7, 0);
  /* #64: @7 = (@7+@11) */
  for (i=0, rr=w7, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #65: output[1][2] = @7 */
  if (res[1]) casadi_copy(w7, 3, res[1]+6);
  /* #66: @22 = zeros(2x3) */
  casadi_clear(w22, 6);
  /* #67: @3 = ones(2x1,1nz) */
  w3 = 1.;
  /* #68: {@14, NULL} = vertsplit(@3) */
  w14 = w3;
  /* #69: @2 = (@2*@14) */
  w2 *= w14;
  /* #70: @4 = (@4*@14) */
  w4 *= w14;
  /* #71: @16 = 00 */
  /* #72: @17 = vertcat(@2, @4, @16) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w4;
  /* #73: @7 = dense(@17) */
  casadi_densify(w17, casadi_s0, w7, 0);
  /* #74: @23 = zeros(3x2) */
  casadi_clear(w23, 6);
  /* #75: @19 = zeros(3x1,0nz) */
  /* #76: @18 = jac_learned_dynamics_differential_drive(@8, @19) */
  arg1[0]=w8;
  arg1[1]=0;
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #77: @19 = 00 */
  /* #78: @24 = 00 */
  /* #79: @25 = 00 */
  /* #80: @2 = vertcat(@19, @24, @25, @14, @16) */
  rr=(&w2);
  *rr++ = w14;
  /* #81: @19 = 00 */
  /* #82: @24 = 00 */
  /* #83: @25 = 00 */
  /* #84: @16 = 00 */
  /* #85: @14 = ones(2x1,1nz) */
  w14 = 1.;
  /* #86: {NULL, @4} = vertsplit(@14) */
  w4 = w14;
  /* #87: @14 = vertcat(@19, @24, @25, @16, @4) */
  rr=(&w14);
  *rr++ = w4;
  /* #88: @17 = horzcat(@2, @14) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w14;
  /* #89: @23 = mac(@18,@17,@23) */
  casadi_mtimes(w18, casadi_s3, w17, casadi_s5, w23, casadi_s4, w, 0);
  /* #90: {@11, @9} = horzsplit(@23) */
  casadi_copy(w23, 3, w11);
  casadi_copy(w23+3, 3, w9);
  /* #91: @7 = (@7+@11) */
  for (i=0, rr=w7, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #92: (@22[:6:2] = @7) */
  for (rr=w22+0, ss=w7; rr!=w22+6; rr+=2) *rr = *ss++;
  /* #93: @19 = 00 */
  /* #94: @24 = 00 */
  /* #95: @2 = vertcat(@19, @24, @4) */
  rr=(&w2);
  *rr++ = w4;
  /* #96: @7 = dense(@2) */
  casadi_densify((&w2), casadi_s6, w7, 0);
  /* #97: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #98: (@22[1:7:2] = @7) */
  for (rr=w22+1, ss=w7; rr!=w22+7; rr+=2) *rr = *ss++;
  /* #99: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<2; ++j) rr[i+j*3] = *cs++;
  /* #100: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #101: @22 = input[2][0] */
  casadi_copy(arg[2], 6, w22);
  /* #102: {@7, @9} = horzsplit(@22) */
  casadi_copy(w22, 3, w7);
  casadi_copy(w22+3, 3, w9);
  /* #103: {@4, @14, @3} = vertsplit(@7) */
  w4 = w7[0];
  w14 = w7[1];
  w3 = w7[2];
  /* #104: @13 = (@2*@3) */
  w13  = (w2*w3);
  /* #105: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #106: @13 = (-@13) */
  w13 = (- w13 );
  /* #107: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #108: @5 = (@1*@3) */
  w5  = (w1*w3);
  /* #109: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #110: @19 = 00 */
  /* #111: @17 = vertcat(@13, @5, @19) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w5;
  /* #112: @7 = dense(@17) */
  casadi_densify(w17, casadi_s0, w7, 0);
  /* #113: @22 = zeros(3x2) */
  casadi_clear(w22, 6);
  /* #114: @19 = zeros(3x1,0nz) */
  /* #115: @18 = jac_learned_dynamics_differential_drive(@8, @19) */
  arg1[0]=w8;
  arg1[1]=0;
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #116: @19 = 00 */
  /* #117: @24 = 00 */
  /* #118: @11 = vertcat(@4, @14, @3, @19, @24) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w3;
  /* #119: {@4, @14, @3} = vertsplit(@9) */
  w4 = w9[0];
  w14 = w9[1];
  w3 = w9[2];
  /* #120: @19 = 00 */
  /* #121: @24 = 00 */
  /* #122: @9 = vertcat(@4, @14, @3, @19, @24) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w3;
  /* #123: @26 = horzcat(@11, @9) */
  rr=w26;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  /* #124: @22 = mac(@18,@26,@22) */
  casadi_mtimes(w18, casadi_s3, w26, casadi_s7, w22, casadi_s4, w, 0);
  /* #125: {@11, @9} = horzsplit(@22) */
  casadi_copy(w22, 3, w11);
  casadi_copy(w22+3, 3, w9);
  /* #126: @7 = (@7+@11) */
  for (i=0, rr=w7, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #127: @2 = (@2*@3) */
  w2 *= w3;
  /* #128: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #129: @2 = (-@2) */
  w2 = (- w2 );
  /* #130: @1 = (@1*@3) */
  w1 *= w3;
  /* #131: @0 = (@0*@1) */
  w0 *= w1;
  /* #132: @19 = 00 */
  /* #133: @17 = vertcat(@2, @0, @19) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w0;
  /* #134: @11 = dense(@17) */
  casadi_densify(w17, casadi_s0, w11, 0);
  /* #135: @11 = (@11+@9) */
  for (i=0, rr=w11, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #136: @22 = horzcat(@7, @11) */
  rr=w22;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  /* #137: @23 = (@23+@22) */
  for (i=0, rr=w23, cs=w22; i<6; ++i) (*rr++) += (*cs++);
  /* #138: output[2][0] = @23 */
  casadi_copy(w23, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dnn_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dnn_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real differential_drive_dnn_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dnn_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dnn_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dnn_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s1;
    case 2: return casadi_s4;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dnn_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s1;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 84;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
