/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) differential_drive_dnn_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* External functions */
int jac_learned_dynamics_differential_drive(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* jac_learned_dynamics_differential_drive:(i0[5],out_o0[3x1,0nz])->(jac_o0_i0[3x5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_learned_dynamics_differential_drive(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* differential_drive_dnn_mpc_expl_vde_adj:(i0[3],i1[3],i2[2],i3[12])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+5, w1, w2, w3, w4, w5, *w6=w+15, *w8=w+20, *w9=w+35, *w10=w+50, w11, w12, w13, w14, w15;
  /* #0: @0 = zeros(5x1) */
  casadi_clear(w0, 5);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #4: @4 = input[2][0] */
  w4 = arg[2] ? arg[2][0] : 0;
  /* #5: @5 = input[2][1] */
  w5 = arg[2] ? arg[2][1] : 0;
  /* #6: @6 = vertcat(@1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @7 = zeros(3x1,0nz) */
  /* #8: @8 = jac_learned_dynamics_differential_drive(@6, @7) */
  arg1[0]=w6;
  arg1[1]=0;
  res1[0]=w8;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #9: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #10: @10 = input[1][0] */
  casadi_copy(arg[1], 3, w10);
  /* #11: @0 = mac(@9,@10,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<5; ++j, ++rr) for (k=0, ss=w9+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*5]**tt++;
  /* #12: {@1, @2, @5, @11, @12} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w5 = w0[2];
  w11 = w0[3];
  w12 = w0[4];
  /* #13: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #14: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #15: @2 = cos(@3) */
  w2 = cos( w3 );
  /* #16: {@1, @13, @14} = vertsplit(@10) */
  w1 = w10[0];
  w13 = w10[1];
  w14 = w10[2];
  /* #17: @15 = (@4*@13) */
  w15  = (w4*w13);
  /* #18: @2 = (@2*@15) */
  w2 *= w15;
  /* #19: @5 = (@5+@2) */
  w5 += w2;
  /* #20: @2 = sin(@3) */
  w2 = sin( w3 );
  /* #21: @4 = (@4*@1) */
  w4 *= w1;
  /* #22: @2 = (@2*@4) */
  w2 *= w4;
  /* #23: @5 = (@5-@2) */
  w5 -= w2;
  /* #24: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #25: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #26: @5 = (@5*@13) */
  w5 *= w13;
  /* #27: @11 = (@11+@5) */
  w11 += w5;
  /* #28: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #29: @3 = (@3*@1) */
  w3 *= w1;
  /* #30: @11 = (@11+@3) */
  w11 += w3;
  /* #31: output[0][3] = @11 */
  if (res[0]) res[0][3] = w11;
  /* #32: @12 = (@12+@14) */
  w12 += w14;
  /* #33: output[0][4] = @12 */
  if (res[0]) res[0][4] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dnn_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dnn_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dnn_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real differential_drive_dnn_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dnn_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dnn_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dnn_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dnn_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int differential_drive_dnn_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 58;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
