/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = {5, 5, 0, 0, 0, 2, 4, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s1[13] = {5, 5, 0, 2, 4, 5, 5, 5, 2, 3, 2, 3, 4};
static const casadi_int casadi_s2[13] = {5, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s7[3] = {5, 0, 0};

/* differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z:(i0[5],i1[5],i2[2],i3[],i4[],i5[9])->(o0[5],o1[5x5,5nz],o2[5x5,5nz],o3[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+16, *w13=w+21, *w16=w+25, *w17=w+28, *w19=w+31, *w20=w+33;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 5, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #5: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #6: @6 = (@1*@5) */
  w6  = (w1*w5);
  /* #7: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = 0.00265655 */
  w8 = 2.6565535794350619e-03;
  /* #9: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #10: @10 = input[2][1] */
  w10 = arg[2] ? arg[2][1] : 0;
  /* #11: @11 = (@9+@10) */
  w11  = (w9+w10);
  /* #12: @8 = (@8*@11) */
  w8 *= w11;
  /* #13: @11 = 0.153432 */
  w11 = 1.5343173312480543e-01;
  /* #14: @9 = (@9-@10) */
  w9 -= w10;
  /* #15: @11 = (@11*@9) */
  w11 *= w9;
  /* #16: @12 = vertcat(@4, @6, @7, @8, @11) */
  rr=w12;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w11;
  /* #17: @0 = (@0-@12) */
  for (i=0, rr=w0, cs=w12; i<5; ++i) (*rr++) -= (*cs++);
  /* #18: output[0][0] = @0 */
  casadi_copy(w0, 5, res[0]);
  /* #19: @0 = zeros(5x5,5nz) */
  casadi_clear(w0, 5);
  /* #20: @4 = sin(@2) */
  w4 = sin( w2 );
  /* #21: @13 = ones(5x1,4nz) */
  casadi_fill(w13, 4, 1.);
  /* #22: {NULL, NULL, @6, NULL, @7} = vertsplit(@13) */
  w6 = w13[2];
  w7 = w13[3];
  /* #23: @4 = (@4*@6) */
  w4 *= w6;
  /* #24: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #25: @4 = (-@4) */
  w4 = (- w4 );
  /* #26: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #27: @2 = (@2*@6) */
  w2 *= w6;
  /* #28: @1 = (@1*@2) */
  w1 *= w2;
  /* #29: @14 = 00 */
  /* #30: @15 = 00 */
  /* #31: @16 = vertcat(@4, @1, @7, @14, @15) */
  rr=w16;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w7;
  /* #32: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #33: @17 = @16[:3] */
  for (rr=w17, ss=w16+0; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #34: (@0[:6:2] = @17) */
  for (rr=w0+0, ss=w17; rr!=w0+6; rr+=2) *rr = *ss++;
  /* #35: @4 = ones(5x1,1nz) */
  w4 = 1.;
  /* #36: {NULL, NULL, NULL, @1, NULL} = vertsplit(@4) */
  w1 = w4;
  /* #37: @3 = (@3*@1) */
  w3 *= w1;
  /* #38: @5 = (@5*@1) */
  w5 *= w1;
  /* #39: @14 = 00 */
  /* #40: @15 = 00 */
  /* #41: @18 = 00 */
  /* #42: @19 = vertcat(@3, @5, @14, @15, @18) */
  rr=w19;
  *rr++ = w3;
  *rr++ = w5;
  /* #43: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) *rr++ = (- *cs++ );
  /* #44: @20 = @19[:2] */
  for (rr=w20, ss=w19+0; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #45: (@0[1:5:2] = @20) */
  for (rr=w0+1, ss=w20; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #46: @12 = @0' */
  casadi_trans(w0,casadi_s1, w12, casadi_s0, iw);
  /* #47: output[1][0] = @12 */
  casadi_copy(w12, 5, res[1]);
  /* #48: @12 = zeros(5x5,5nz) */
  casadi_clear(w12, 5);
  /* #49: @0 = ones(5x1) */
  casadi_fill(w0, 5, 1.);
  /* #50: (@12[:5] = @0) */
  for (rr=w12+0, ss=w0; rr!=w12+5; rr+=1) *rr = *ss++;
  /* #51: @0 = @12' */
  casadi_trans(w12,casadi_s2, w0, casadi_s2, iw);
  /* #52: output[2][0] = @0 */
  casadi_copy(w0, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 35;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
