/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) differential_drive_dynamics_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {6, 2, 0, 2, 4, 3, 4, 3, 4};
static const casadi_int casadi_s1[13] = {2, 6, 0, 0, 0, 0, 2, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[15] = {6, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[11] = {6, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[17] = {6, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[27] = {6, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* differential_drive_dynamics_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4[6])->(o0[6],o1[6x6,18nz],o2[6x2,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+14, *w9=w+50, *w10=w+56, *w11=w+62, *w12=w+68, *w13=w+74, *w14=w+80, w15, w16, w17, w18, w19, *w20=w+91, *w25=w+95, *w26=w+97, *w27=w+99, *w28=w+103, *w29=w+113, *w30=w+125, *w31=w+128, *w32=w+131;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = 0.00265655 */
  w4 = 2.6565535794350619e-03;
  /* #11: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #12: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #13: @7 = (@5+@6) */
  w7  = (w5+w6);
  /* #14: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #15: output[0][3] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #16: @7 = 0.153432 */
  w7 = 1.5343173312480543e-01;
  /* #17: @5 = (@5-@6) */
  w5 -= w6;
  /* #18: @5 = (@7*@5) */
  w5  = (w7*w5);
  /* #19: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #20: @5 = 0 */
  w5 = 0.;
  /* #21: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #22: @8 = input[1][0] */
  casadi_copy(arg[1], 36, w8);
  /* #23: {@9, @10, @11, @12, @13, @14} = horzsplit(@8) */
  casadi_copy(w8, 6, w9);
  casadi_copy(w8+6, 6, w10);
  casadi_copy(w8+12, 6, w11);
  casadi_copy(w8+18, 6, w12);
  casadi_copy(w8+24, 6, w13);
  casadi_copy(w8+30, 6, w14);
  /* #24: {NULL, NULL, @5, @6, @15, NULL} = vertsplit(@9) */
  w5 = w9[2];
  w6 = w9[3];
  w15 = w9[4];
  /* #25: @16 = (@2*@6) */
  w16  = (w2*w6);
  /* #26: @17 = sin(@1) */
  w17 = sin( w1 );
  /* #27: @18 = (@17*@5) */
  w18  = (w17*w5);
  /* #28: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #29: @16 = (@16-@18) */
  w16 -= w18;
  /* #30: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #31: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #32: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #33: @5 = (@16*@5) */
  w5  = (w16*w5);
  /* #34: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #35: @6 = (@6+@5) */
  w6 += w5;
  /* #36: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #37: output[1][2] = @15 */
  if (res[1]) res[1][2] = w15;
  /* #38: {NULL, NULL, @15, @6, @5, NULL} = vertsplit(@10) */
  w15 = w10[2];
  w6 = w10[3];
  w5 = w10[4];
  /* #39: @18 = (@2*@6) */
  w18  = (w2*w6);
  /* #40: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #41: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #42: @18 = (@18-@19) */
  w18 -= w19;
  /* #43: output[1][3] = @18 */
  if (res[1]) res[1][3] = w18;
  /* #44: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #45: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #46: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #47: @6 = (@6+@15) */
  w6 += w15;
  /* #48: output[1][4] = @6 */
  if (res[1]) res[1][4] = w6;
  /* #49: output[1][5] = @5 */
  if (res[1]) res[1][5] = w5;
  /* #50: {NULL, NULL, @5, @6, @15, NULL} = vertsplit(@11) */
  w5 = w11[2];
  w6 = w11[3];
  w15 = w11[4];
  /* #51: @18 = (@2*@6) */
  w18  = (w2*w6);
  /* #52: @19 = (@17*@5) */
  w19  = (w17*w5);
  /* #53: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #54: @18 = (@18-@19) */
  w18 -= w19;
  /* #55: output[1][6] = @18 */
  if (res[1]) res[1][6] = w18;
  /* #56: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #57: @5 = (@16*@5) */
  w5  = (w16*w5);
  /* #58: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #59: @6 = (@6+@5) */
  w6 += w5;
  /* #60: output[1][7] = @6 */
  if (res[1]) res[1][7] = w6;
  /* #61: output[1][8] = @15 */
  if (res[1]) res[1][8] = w15;
  /* #62: {NULL, NULL, @15, @6, @5, NULL} = vertsplit(@12) */
  w15 = w12[2];
  w6 = w12[3];
  w5 = w12[4];
  /* #63: @18 = (@2*@6) */
  w18  = (w2*w6);
  /* #64: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #65: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #66: @18 = (@18-@19) */
  w18 -= w19;
  /* #67: output[1][9] = @18 */
  if (res[1]) res[1][9] = w18;
  /* #68: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #69: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #70: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #71: @6 = (@6+@15) */
  w6 += w15;
  /* #72: output[1][10] = @6 */
  if (res[1]) res[1][10] = w6;
  /* #73: output[1][11] = @5 */
  if (res[1]) res[1][11] = w5;
  /* #74: {NULL, NULL, @5, @6, @15, NULL} = vertsplit(@13) */
  w5 = w13[2];
  w6 = w13[3];
  w15 = w13[4];
  /* #75: @18 = (@2*@6) */
  w18  = (w2*w6);
  /* #76: @19 = (@17*@5) */
  w19  = (w17*w5);
  /* #77: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #78: @18 = (@18-@19) */
  w18 -= w19;
  /* #79: output[1][12] = @18 */
  if (res[1]) res[1][12] = w18;
  /* #80: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #81: @5 = (@16*@5) */
  w5  = (w16*w5);
  /* #82: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #83: @6 = (@6+@5) */
  w6 += w5;
  /* #84: output[1][13] = @6 */
  if (res[1]) res[1][13] = w6;
  /* #85: output[1][14] = @15 */
  if (res[1]) res[1][14] = w15;
  /* #86: {NULL, NULL, @15, @6, @5, NULL} = vertsplit(@14) */
  w15 = w14[2];
  w6 = w14[3];
  w5 = w14[4];
  /* #87: @18 = (@2*@6) */
  w18  = (w2*w6);
  /* #88: @17 = (@17*@15) */
  w17 *= w15;
  /* #89: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #90: @18 = (@18-@17) */
  w18 -= w17;
  /* #91: output[1][15] = @18 */
  if (res[1]) res[1][15] = w18;
  /* #92: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #93: @16 = (@16*@15) */
  w16 *= w15;
  /* #94: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #95: @6 = (@6+@16) */
  w6 += w16;
  /* #96: output[1][16] = @6 */
  if (res[1]) res[1][16] = w6;
  /* #97: output[1][17] = @5 */
  if (res[1]) res[1][17] = w5;
  /* #98: @20 = zeros(2x6,4nz) */
  casadi_clear(w20, 4);
  /* #99: @21 = 00 */
  /* #100: @22 = 00 */
  /* #101: @23 = 00 */
  /* #102: @5 = ones(2x1,1nz) */
  w5 = 1.;
  /* #103: {@6, NULL} = vertsplit(@5) */
  w6 = w5;
  /* #104: @5 = (@4*@6) */
  w5  = (w4*w6);
  /* #105: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #106: @24 = 00 */
  /* #107: @25 = vertcat(@21, @22, @23, @5, @6, @24) */
  rr=w25;
  *rr++ = w5;
  *rr++ = w6;
  /* #108: @26 = @25[:2] */
  for (rr=w26, ss=w25+0; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #109: (@20[:4:2] = @26) */
  for (rr=w20+0, ss=w26; rr!=w20+4; rr+=2) *rr = *ss++;
  /* #110: @21 = 00 */
  /* #111: @22 = 00 */
  /* #112: @23 = 00 */
  /* #113: @5 = ones(2x1,1nz) */
  w5 = 1.;
  /* #114: {NULL, @6} = vertsplit(@5) */
  w6 = w5;
  /* #115: @4 = (@4*@6) */
  w4 *= w6;
  /* #116: @7 = (@7*@6) */
  w7 *= w6;
  /* #117: @7 = (-@7) */
  w7 = (- w7 );
  /* #118: @24 = 00 */
  /* #119: @26 = vertcat(@21, @22, @23, @4, @7, @24) */
  rr=w26;
  *rr++ = w4;
  *rr++ = w7;
  /* #120: @25 = @26[:2] */
  for (rr=w25, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #121: (@20[1:5:2] = @25) */
  for (rr=w20+1, ss=w25; rr!=w20+5; rr+=2) *rr = *ss++;
  /* #122: @27 = @20' */
  casadi_trans(w20,casadi_s1, w27, casadi_s0, iw);
  /* #123: @28 = project(@27) */
  casadi_project(w27, casadi_s0, w28, casadi_s2, w);
  /* #124: @29 = input[2][0] */
  casadi_copy(arg[2], 12, w29);
  /* #125: {@14, @13} = horzsplit(@29) */
  casadi_copy(w29, 6, w14);
  casadi_copy(w29+6, 6, w13);
  /* #126: {NULL, NULL, @4, @7, @6, NULL} = vertsplit(@14) */
  w4 = w14[2];
  w7 = w14[3];
  w6 = w14[4];
  /* #127: @5 = (@2*@7) */
  w5  = (w2*w7);
  /* #128: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #129: @15 = (@16*@4) */
  w15  = (w16*w4);
  /* #130: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #131: @5 = (@5-@15) */
  w5 -= w15;
  /* #132: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #133: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #134: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #135: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #136: @7 = (@7+@4) */
  w7 += w4;
  /* #137: @21 = 00 */
  /* #138: @22 = 00 */
  /* #139: @23 = 00 */
  /* #140: @30 = vertcat(@5, @7, @6, @21, @22, @23) */
  rr=w30;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w6;
  /* #141: {NULL, NULL, @5, @7, @6, NULL} = vertsplit(@13) */
  w5 = w13[2];
  w7 = w13[3];
  w6 = w13[4];
  /* #142: @2 = (@2*@7) */
  w2 *= w7;
  /* #143: @16 = (@16*@5) */
  w16 *= w5;
  /* #144: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #145: @2 = (@2-@16) */
  w2 -= w16;
  /* #146: @3 = (@3*@7) */
  w3 *= w7;
  /* #147: @1 = (@1*@5) */
  w1 *= w5;
  /* #148: @0 = (@0*@1) */
  w0 *= w1;
  /* #149: @3 = (@3+@0) */
  w3 += w0;
  /* #150: @21 = 00 */
  /* #151: @22 = 00 */
  /* #152: @23 = 00 */
  /* #153: @31 = vertcat(@2, @3, @6, @21, @22, @23) */
  rr=w31;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w6;
  /* #154: @13 = horzcat(@30, @31) */
  rr=w13;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  /* #155: @32 = project(@13) */
  casadi_project(w13, casadi_s3, w32, casadi_s2, w);
  /* #156: @28 = (@28+@32) */
  for (i=0, rr=w28, cs=w32; i<10; ++i) (*rr++) += (*cs++);
  /* #157: output[2][0] = @28 */
  casadi_copy(w28, 10, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void differential_drive_dynamics_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dynamics_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int differential_drive_dynamics_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real differential_drive_dynamics_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dynamics_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* differential_drive_dynamics_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dynamics_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* differential_drive_dynamics_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s8;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int differential_drive_dynamics_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 141;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
