/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_dynamics_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* racecar_dynamics_expl_ode_fun:(i0[6],i1[4],i2[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #5: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #6: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #7: @2 = (@2-@4) */
  w2 -= w4;
  /* #8: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #9: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #10: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #11: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #12: @1 = (@3*@1) */
  w1  = (w3*w1);
  /* #13: @2 = (@2+@1) */
  w2 += w1;
  /* #14: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #15: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #16: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #17: @1 = 0.25 */
  w1 = 2.5000000000000000e-01;
  /* #18: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #19: @5 = 0.3 */
  w5 = 2.9999999999999999e-01;
  /* #20: @4 = (@4/@5) */
  w4 /= w5;
  /* #21: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #22: @6 = 0.3 */
  w6 = 2.9999999999999999e-01;
  /* #23: @5 = (@5/@6) */
  w5 /= w6;
  /* #24: @4 = (@4+@5) */
  w4 += w5;
  /* #25: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #26: @6 = 0.3 */
  w6 = 2.9999999999999999e-01;
  /* #27: @5 = (@5/@6) */
  w5 /= w6;
  /* #28: @4 = (@4+@5) */
  w4 += w5;
  /* #29: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #30: @6 = 0.3 */
  w6 = 2.9999999999999999e-01;
  /* #31: @5 = (@5/@6) */
  w5 /= w6;
  /* #32: @4 = (@4+@5) */
  w4 += w5;
  /* #33: @1 = (@1*@4) */
  w1 *= w4;
  /* #34: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #35: @1 = (@1-@4) */
  w1 -= w4;
  /* #36: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #37: @1 = 0.25 */
  w1 = 2.5000000000000000e-01;
  /* #38: @4 = 50000 */
  w4 = 50000.;
  /* #39: @5 = 1.2 */
  w5 = 1.2000000000000000e+00;
  /* #40: @5 = (@5*@2) */
  w5 *= w2;
  /* #41: @5 = (@3+@5) */
  w5  = (w3+w5);
  /* #42: @4 = (@4*@5) */
  w4 *= w5;
  /* #43: @4 = (@4/@0) */
  w4 /= w0;
  /* #44: @5 = 50000 */
  w5 = 50000.;
  /* #45: @6 = 1.6 */
  w6 = 1.6000000000000001e+00;
  /* #46: @6 = (@6*@2) */
  w6 *= w2;
  /* #47: @3 = (@3-@6) */
  w3 -= w6;
  /* #48: @5 = (@5*@3) */
  w5 *= w3;
  /* #49: @5 = (@5/@0) */
  w5 /= w0;
  /* #50: @3 = (@4+@5) */
  w3  = (w4+w5);
  /* #51: @1 = (@1*@3) */
  w1 *= w3;
  /* #52: @2 = (@2*@0) */
  w2 *= w0;
  /* #53: @1 = (@1+@2) */
  w1 += w2;
  /* #54: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #55: @1 = 17.0503 */
  w1 = 1.7050298380221655e+01;
  /* #56: @2 = 1.2 */
  w2 = 1.2000000000000000e+00;
  /* #57: @2 = (@2*@4) */
  w2 *= w4;
  /* #58: @4 = 1.6 */
  w4 = 1.6000000000000001e+00;
  /* #59: @4 = (@4*@5) */
  w4 *= w5;
  /* #60: @2 = (@2-@4) */
  w2 -= w4;
  /* #61: @1 = (@1*@2) */
  w1 *= w2;
  /* #62: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_dynamics_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int racecar_dynamics_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real racecar_dynamics_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_dynamics_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_dynamics_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_dynamics_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_dynamics_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 7;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
