/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_dynamics_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {10, 1, 0, 8, 2, 3, 4, 5, 6, 7, 8, 9};

/* racecar_dynamics_expl_vde_adj:(i0[6],i1[6],i2[4],i3[])->(o0[10x1,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 6, w3);
  /* #4: {@4, @5, @6, @7, @8, @9} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  /* #5: @10 = (@2*@5) */
  w10  = (w2*w5);
  /* #6: @1 = (@1*@10) */
  w1 *= w10;
  /* #7: @10 = sin(@0) */
  w10 = sin( w0 );
  /* #8: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #9: @12 = (@11*@5) */
  w12  = (w11*w5);
  /* #10: @10 = (@10*@12) */
  w10 *= w12;
  /* #11: @1 = (@1-@10) */
  w1 -= w10;
  /* #12: @10 = cos(@0) */
  w10 = cos( w0 );
  /* #13: @12 = (@11*@4) */
  w12  = (w11*w4);
  /* #14: @10 = (@10*@12) */
  w10 *= w12;
  /* #15: @1 = (@1-@10) */
  w1 -= w10;
  /* #16: @10 = sin(@0) */
  w10 = sin( w0 );
  /* #17: @12 = (@2*@4) */
  w12  = (w2*w4);
  /* #18: @10 = (@10*@12) */
  w10 *= w12;
  /* #19: @1 = (@1-@10) */
  w1 -= w10;
  /* #20: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #21: @1 = input[0][5] */
  w1 = arg[0] ? arg[0][5] : 0;
  /* #22: @10 = (@1*@8) */
  w10  = (w1*w8);
  /* #23: @12 = 50000 */
  w12 = 50000.;
  /* #24: @13 = 1.6 */
  w13 = 1.6000000000000001e+00;
  /* #25: @14 = (@13*@1) */
  w14  = (w13*w1);
  /* #26: @14 = (@11-@14) */
  w14  = (w11-w14);
  /* #27: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #28: @14 = (@14/@2) */
  w14 /= w2;
  /* #29: @14 = (@14/@2) */
  w14 /= w2;
  /* #30: @15 = 0.25 */
  w15 = 2.5000000000000000e-01;
  /* #31: @15 = (@15*@8) */
  w15 *= w8;
  /* #32: @16 = 1.6 */
  w16 = 1.6000000000000001e+00;
  /* #33: @17 = 17.0503 */
  w17 = 1.7050298380221655e+01;
  /* #34: @17 = (@17*@9) */
  w17 *= w9;
  /* #35: @16 = (@16*@17) */
  w16 *= w17;
  /* #36: @16 = (@15-@16) */
  w16  = (w15-w16);
  /* #37: @14 = (@14*@16) */
  w14 *= w16;
  /* #38: @10 = (@10-@14) */
  w10 -= w14;
  /* #39: @14 = 50000 */
  w14 = 50000.;
  /* #40: @9 = 1.2 */
  w9 = 1.2000000000000000e+00;
  /* #41: @18 = (@9*@1) */
  w18  = (w9*w1);
  /* #42: @18 = (@11+@18) */
  w18  = (w11+w18);
  /* #43: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #44: @18 = (@18/@2) */
  w18 /= w2;
  /* #45: @18 = (@18/@2) */
  w18 /= w2;
  /* #46: @19 = 1.2 */
  w19 = 1.2000000000000000e+00;
  /* #47: @19 = (@19*@17) */
  w19 *= w17;
  /* #48: @19 = (@19+@15) */
  w19 += w15;
  /* #49: @18 = (@18*@19) */
  w18 *= w19;
  /* #50: @10 = (@10-@18) */
  w10 -= w18;
  /* #51: @18 = sin(@0) */
  w18 = sin( w0 );
  /* #52: @18 = (@18*@5) */
  w18 *= w5;
  /* #53: @10 = (@10+@18) */
  w10 += w18;
  /* #54: @18 = cos(@0) */
  w18 = cos( w0 );
  /* #55: @18 = (@18*@4) */
  w18 *= w4;
  /* #56: @10 = (@10+@18) */
  w10 += w18;
  /* #57: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #58: @16 = (@16/@2) */
  w16 /= w2;
  /* #59: @12 = (@12*@16) */
  w12 *= w16;
  /* #60: @19 = (@19/@2) */
  w19 /= w2;
  /* #61: @14 = (@14*@19) */
  w14 *= w19;
  /* #62: @19 = (@12+@14) */
  w19  = (w12+w14);
  /* #63: @1 = (@1*@7) */
  w1 *= w7;
  /* #64: @19 = (@19-@1) */
  w19 -= w1;
  /* #65: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #66: @1 = (@1*@5) */
  w1 *= w5;
  /* #67: @19 = (@19+@1) */
  w19 += w1;
  /* #68: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #69: @0 = (@0*@4) */
  w0 *= w4;
  /* #70: @19 = (@19-@0) */
  w19 -= w0;
  /* #71: output[0][2] = @19 */
  if (res[0]) res[0][2] = w19;
  /* #72: @2 = (@2*@8) */
  w2 *= w8;
  /* #73: @13 = (@13*@12) */
  w13 *= w12;
  /* #74: @2 = (@2-@13) */
  w2 -= w13;
  /* #75: @9 = (@9*@14) */
  w9 *= w14;
  /* #76: @2 = (@2+@9) */
  w2 += w9;
  /* #77: @11 = (@11*@7) */
  w11 *= w7;
  /* #78: @2 = (@2-@11) */
  w2 -= w11;
  /* #79: @2 = (@2+@6) */
  w2 += w6;
  /* #80: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #81: @2 = 3.33333 */
  w2 = 3.3333333333333335e+00;
  /* #82: @6 = 0.25 */
  w6 = 2.5000000000000000e-01;
  /* #83: @6 = (@6*@7) */
  w6 *= w7;
  /* #84: @2 = (@2*@6) */
  w2 *= w6;
  /* #85: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #86: @2 = 3.33333 */
  w2 = 3.3333333333333335e+00;
  /* #87: @2 = (@2*@6) */
  w2 *= w6;
  /* #88: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #89: @2 = 3.33333 */
  w2 = 3.3333333333333335e+00;
  /* #90: @2 = (@2*@6) */
  w2 *= w6;
  /* #91: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #92: @2 = 3.33333 */
  w2 = 3.3333333333333335e+00;
  /* #93: @2 = (@2*@6) */
  w2 *= w6;
  /* #94: output[0][7] = @2 */
  if (res[0]) res[0][7] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_dynamics_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_dynamics_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int racecar_dynamics_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real racecar_dynamics_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_dynamics_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_dynamics_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_dynamics_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_dynamics_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_dynamics_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 25;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
