/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) four_wheel_drive_dynamics_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};

/* four_wheel_drive_dynamics_constr_h_fun:(i0[5],i1[4],i2[],i3[9])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[3][0] */
  casadi_copy(arg[3], 9, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @2 = (@0-@2) */
  w2  = (w0-w2);
  /* #4: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #5: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #6: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @4 = (@3-@4) */
  w4  = (w3-w4);
  /* #8: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #9: @2 = (@2+@4) */
  w2 += w4;
  /* #10: @4 = 0.3 */
  w4 = 2.9999999999999999e-01;
  /* #11: @5 = @1[6] */
  for (rr=(&w5), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #12: @4 = (@4+@5) */
  w4 += w5;
  /* #13: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #14: @2 = (@2-@4) */
  w2 -= w4;
  /* #15: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #16: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = (@0-@2) */
  w2  = (w0-w2);
  /* #18: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #19: @4 = @1[3] */
  for (rr=(&w4), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #20: @4 = (@3-@4) */
  w4  = (w3-w4);
  /* #21: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #22: @2 = (@2+@4) */
  w2 += w4;
  /* #23: @4 = 0.3 */
  w4 = 2.9999999999999999e-01;
  /* #24: @5 = @1[7] */
  for (rr=(&w5), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #25: @4 = (@4+@5) */
  w4 += w5;
  /* #26: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #27: @2 = (@2-@4) */
  w2 -= w4;
  /* #28: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #29: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #30: @0 = (@0-@2) */
  w0 -= w2;
  /* #31: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #32: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #33: @3 = (@3-@2) */
  w3 -= w2;
  /* #34: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #35: @0 = (@0+@3) */
  w0 += w3;
  /* #36: @3 = 0.3 */
  w3 = 2.9999999999999999e-01;
  /* #37: @2 = @1[8] */
  for (rr=(&w2), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #38: @3 = (@3+@2) */
  w3 += w2;
  /* #39: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #40: @0 = (@0-@3) */
  w0 -= w3;
  /* #41: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void four_wheel_drive_dynamics_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int four_wheel_drive_dynamics_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real four_wheel_drive_dynamics_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* four_wheel_drive_dynamics_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* four_wheel_drive_dynamics_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int four_wheel_drive_dynamics_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 14;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
